classdef EstimationCasesEnum < int32
   enumeration
      COMP_NONE(1), 
      FORCE_PLAIN_P(2), POS_V_PLAIN_P(3), FIX_IMP_PLAIN_P(4), ADM_PLAIN_P(5), FORCE_INT_PLAIN_P(6), 
      FORCE_MULTICH8(7),POS_V_MULTICH8(8), FIX_IMP_MULTICH8(9), ADM_MULTICH8(10), FORCE_INT_MULTICH8(11)
   end
end